name: Publish Package to npmjs
on:
  workflow_dispatch:
    inputs:
        version:
            description: "Type of SemVer Change"
            required: true
            default: 'bugfix'
            type: choice
            options:
            - major
            - minor
            - bugfix
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: node ./scripts/adjustVersionNumber.js --version=${{inputs.version}} 
      - run: npm run rollup
      - run: |
          cd dist
          npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}